//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 13/06/2013 11:49:17
// This source code was auto-generated by NHQG (NHibernate.Query.Generator), Version 1.9.1.0.
// 
namespace Debugging.Tests {
    using NHibernate = global::NHibernate;
    
    
    public partial class Where {
        
        /// <summary>
        /// Query helper for member Where.NHQGWithNHOne
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public static Root_Query_NHQGWithNHOne NHQGWithNHOne {
            get {
                return new Root_Query_NHQGWithNHOne();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_NHQGWithNHOne
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Query_NHQGWithNHOne<T1> : QueryBuilder<T1>
         {
            
            /// <summary>
            /// Query helper for member Query_NHQGWithNHOne..ctor
            /// </summary>
            public Query_NHQGWithNHOne() : 
                    this(null, "this", null) {
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithNHOne..ctor
            /// </summary>
            public Query_NHQGWithNHOne(QueryBuilder<T1> parent, string name, string associationPath) : 
                    base(parent, name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithNHOne..ctor
            /// </summary>
            public Query_NHQGWithNHOne(QueryBuilder<T1> parent, string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(parent, name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithNHOne.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Name {
                get {
                    string temp = associationPath;
                    PropertyQueryBuilder<T1> child = new PropertyQueryBuilder<T1>(null, "Name", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithNHOne.
            /// </summary>
            public virtual IdQueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    IdQueryBuilder<T1> child = new IdQueryBuilder<T1>(null, "Id", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            public virtual Query_Collection_NHQGWithNHManies NHQGWithNHManies {
                get {
                    string temp = associationPath;
                    temp = (temp + ".NHQGWithNHManies");
                    return new Query_Collection_NHQGWithNHManies(this, "NHQGWithNHManies", temp);
                }
            }
            
            [System.CLSCompliantAttribute(false)]
            public class Query_Collection_NHQGWithNHManies : CollectionQueryBuilder<T1> {
                
                public Query_Collection_NHQGWithNHManies(QueryBuilder<T1> parent, string name, string associationPath) : 
                        base(parent, name, associationPath) {
                }
                
                public virtual Query_NHQGWithNHMany<T1> With() {
                    Query_NHQGWithNHMany<T1> query = new Query_NHQGWithNHMany<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_NHQGWithNHMany<T1> With(NHibernate.SqlCommand.JoinType joinType) {
                    Query_NHQGWithNHMany<T1> query = new Query_NHQGWithNHMany<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_NHQGWithNHMany<T1> With(NHibernate.FetchMode fetchMode) {
                    Query_NHQGWithNHMany<T1> query = new Query_NHQGWithNHMany<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = fetchMode;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_NHQGWithNHMany<T1> With(NHibernate.SqlCommand.JoinType joinType, NHibernate.FetchMode fetchMode) {
                    Query_NHQGWithNHMany<T1> query = new Query_NHQGWithNHMany<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = fetchMode;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_NHQGWithNHOne
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Root_Query_NHQGWithNHOne : Query_NHQGWithNHOne<Debugging.Tests.NHQGWithNHOne> {
        }
    }
    
    public partial class OrderBy {
        
        /// <summary>
        /// Query helper for member OrderBy.NHQGWithNHOne
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NHQGWithNHOne {
            
            /// <summary>
            /// Query helper for member NHQGWithNHOne.Name
            /// </summary>
            public static OrderByClause Name {
                get {
                    return new OrderByClause("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NHQGWithNHOne.Id
            /// </summary>
            public static OrderByClause Id {
                get {
                    return new OrderByClause("Id");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// <summary>
        /// Query helper for member ProjectBy.NHQGWithNHOne
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NHQGWithNHOne {
            
            /// <summary>
            /// Query helper for member NHQGWithNHOne.Name
            /// </summary>
            public static PropertyProjectionBuilder Name {
                get {
                    return new PropertyProjectionBuilder("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NHQGWithNHOne.Id
            /// </summary>
            public static NumericPropertyProjectionBuilder Id {
                get {
                    return new NumericPropertyProjectionBuilder("Id");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// <summary>
        /// Query helper for member GroupBy.NHQGWithNHOne
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NHQGWithNHOne {
            
            /// <summary>
            /// Query helper for member NHQGWithNHOne.Name
            /// </summary>
            public static NHibernate.Criterion.IProjection Name {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NHQGWithNHOne.Id
            /// </summary>
            public static NHibernate.Criterion.IProjection Id {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Id");
                }
            }
        }
    }
}
