//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 13/06/2013 11:40:20
// This source code was auto-generated by NHQG (NHibernate.Query.Generator), Version 1.9.1.0.
// 
namespace Debugging.Tests {
    using NHibernate = global::NHibernate;
    
    
    public partial class Where {
        
        /// <summary>
        /// Query helper for member Where.NHQGWithARMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public static Root_Query_NHQGWithARMany NHQGWithARMany {
            get {
                return new Root_Query_NHQGWithARMany();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_NHQGWithARMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Query_NHQGWithARMany<T1> : QueryBuilder<T1>
         {
            
            /// <summary>
            /// Query helper for member Query_NHQGWithARMany..ctor
            /// </summary>
            public Query_NHQGWithARMany() : 
                    this(null, "this", null) {
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithARMany..ctor
            /// </summary>
            public Query_NHQGWithARMany(QueryBuilder<T1> parent, string name, string associationPath) : 
                    base(parent, name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithARMany..ctor
            /// </summary>
            public Query_NHQGWithARMany(QueryBuilder<T1> parent, string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(parent, name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithARMany.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Name {
                get {
                    string temp = associationPath;
                    PropertyQueryBuilder<T1> child = new PropertyQueryBuilder<T1>(null, "Name", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithARMany.
            /// </summary>
            public virtual IdQueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    IdQueryBuilder<T1> child = new IdQueryBuilder<T1>(null, "Id", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithARMany.
            /// </summary>
            public virtual Query_NHQGWithAROne<T1> NHQGWithAROne {
                get {
                    string temp = associationPath;
                    temp = ((temp + ".") 
                                + "NHQGWithAROne");
                    Query_NHQGWithAROne<T1> child = new Query_NHQGWithAROne<T1>(null, "NHQGWithAROne", temp, true);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_NHQGWithARMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Root_Query_NHQGWithARMany : Query_NHQGWithARMany<Debugging.Tests.NHQGWithARMany> {
        }
    }
    
    public partial class OrderBy {
        
        /// <summary>
        /// Query helper for member OrderBy.NHQGWithARMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NHQGWithARMany {
            
            /// <summary>
            /// Query helper for member NHQGWithARMany.Name
            /// </summary>
            public static OrderByClause Name {
                get {
                    return new OrderByClause("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NHQGWithARMany.Id
            /// </summary>
            public static OrderByClause Id {
                get {
                    return new OrderByClause("Id");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// <summary>
        /// Query helper for member ProjectBy.NHQGWithARMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NHQGWithARMany {
            
            /// <summary>
            /// Query helper for member NHQGWithARMany.Name
            /// </summary>
            public static PropertyProjectionBuilder Name {
                get {
                    return new PropertyProjectionBuilder("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NHQGWithARMany.Id
            /// </summary>
            public static NumericPropertyProjectionBuilder Id {
                get {
                    return new NumericPropertyProjectionBuilder("Id");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// <summary>
        /// Query helper for member GroupBy.NHQGWithARMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NHQGWithARMany {
            
            /// <summary>
            /// Query helper for member NHQGWithARMany.Name
            /// </summary>
            public static NHibernate.Criterion.IProjection Name {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NHQGWithARMany.Id
            /// </summary>
            public static NHibernate.Criterion.IProjection Id {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Id");
                }
            }
        }
    }
}
