//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 13/06/2013 11:49:17
// This source code was auto-generated by NHQG (NHibernate.Query.Generator), Version 1.9.1.0.
// 
namespace Debugging.Tests {
    using NHibernate = global::NHibernate;
    
    
    public partial class Where {
        
        /// <summary>
        /// Query helper for member Where.NHQGWithNHMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public static Root_Query_NHQGWithNHMany NHQGWithNHMany {
            get {
                return new Root_Query_NHQGWithNHMany();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_NHQGWithNHMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Query_NHQGWithNHMany<T1> : QueryBuilder<T1>
         {
            
            /// <summary>
            /// Query helper for member Query_NHQGWithNHMany..ctor
            /// </summary>
            public Query_NHQGWithNHMany() : 
                    this(null, "this", null) {
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithNHMany..ctor
            /// </summary>
            public Query_NHQGWithNHMany(QueryBuilder<T1> parent, string name, string associationPath) : 
                    base(parent, name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithNHMany..ctor
            /// </summary>
            public Query_NHQGWithNHMany(QueryBuilder<T1> parent, string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(parent, name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithNHMany.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Name {
                get {
                    string temp = associationPath;
                    PropertyQueryBuilder<T1> child = new PropertyQueryBuilder<T1>(null, "Name", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithNHMany.
            /// </summary>
            public virtual IdQueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    IdQueryBuilder<T1> child = new IdQueryBuilder<T1>(null, "Id", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            /// <summary>
            /// Query helper for member Query_NHQGWithNHMany.
            /// </summary>
            public virtual Query_NHQGWithNHOne<T1> NHQGWithNHOne {
                get {
                    string temp = associationPath;
                    temp = ((temp + ".") 
                                + "NHQGWithNHOne");
                    Query_NHQGWithNHOne<T1> child = new Query_NHQGWithNHOne<T1>(null, "NHQGWithNHOne", temp, true);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_NHQGWithNHMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Root_Query_NHQGWithNHMany : Query_NHQGWithNHMany<Debugging.Tests.NHQGWithNHMany> {
        }
    }
    
    public partial class OrderBy {
        
        /// <summary>
        /// Query helper for member OrderBy.NHQGWithNHMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NHQGWithNHMany {
            
            /// <summary>
            /// Query helper for member NHQGWithNHMany.Name
            /// </summary>
            public static OrderByClause Name {
                get {
                    return new OrderByClause("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NHQGWithNHMany.Id
            /// </summary>
            public static OrderByClause Id {
                get {
                    return new OrderByClause("Id");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// <summary>
        /// Query helper for member ProjectBy.NHQGWithNHMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NHQGWithNHMany {
            
            /// <summary>
            /// Query helper for member NHQGWithNHMany.Name
            /// </summary>
            public static PropertyProjectionBuilder Name {
                get {
                    return new PropertyProjectionBuilder("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NHQGWithNHMany.Id
            /// </summary>
            public static NumericPropertyProjectionBuilder Id {
                get {
                    return new NumericPropertyProjectionBuilder("Id");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// <summary>
        /// Query helper for member GroupBy.NHQGWithNHMany
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NHQGWithNHMany {
            
            /// <summary>
            /// Query helper for member NHQGWithNHMany.Name
            /// </summary>
            public static NHibernate.Criterion.IProjection Name {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NHQGWithNHMany.Id
            /// </summary>
            public static NHibernate.Criterion.IProjection Id {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Id");
                }
            }
        }
    }
}
